name: Carat
version: "1.1"
license: "GPL v@.0"
date: 2019-11-10
description: |
    Crystallographic AlgoRithms And Tables

maintainers:
    - name: Dominik Berhardt
      url: https://www.mathb.rwth-aachen.de/cms/MATHB/Der-Lehrstuhl/Team/Wissenschaftliche-Beschaeftigte/~rnsg/Dominik-Bernhardt/lidx/1/

GAP: ">=4.8.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.1"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "orb"
      version: ">= 4.2"
      url: "https://gap-packages.github.io/orb"

www: https://lbfm-rwth.github.io/Carat/
readme: README.md
packageinfo: https://lbfm-rwth.github.io/Carat/PackageInfo.g
github: https://github.com/lbfm-rwth/Carat

downloads:
    - name: .tar.gz
      url: https://github.com/lbfm-rwth/Carat/releases/download/v1.1/Carat-1.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/lbfm-rwth/Carat/releases/download/v1.1/Carat-1.1.tar.bz2

abstract: |
    Carat is a computer package whichhandles enumeration, construction, recognition,and comparison problems for crystallographic groupsup to dimension 6. The name CARAT itself is anacronym for Crystallographic AlgoRithms And Tables.

status: other
doc-html: tex/index.html
doc-pdf: doc/manual.pdf
keywords: |
    GitHub Pages, CARAT.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ber19</span>]   <b class='BibAuthor'>Berhardt, D.</b>,
     <i class='BibTitle'>Carat, Crystallographic AlgoRithms And Tables,
             Version 1.1</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://lbfm-rwth.github.io/Carat/">https://lbfm-rwth.github.io/Carat/</a></span>.
    </p>
    

bibtex: |
    @misc{ Carat1.1,
      author =           {Berhardt, D.},
      title =            {{Carat}, Crystallographic AlgoRithms And Tables, {V}ersion 1.1},
      month =            {Nov},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href {https://lbfm-rwth.github.io/Carat/} {\texttt{https://lbfm-rwth.github.io/}\discretionary {}{}{}\texttt{Carat/}}},
      keywords =         {GitHub Pages; CARAT},
      printedkey =       {Ber19}
    }

